header = "// SPDX-License-Identifier: MIT OR Apache-2.0"
sys_includes = ["stddef.h", "stdint.h", "stdlib.h"]
no_includes = true
include_guard = "LEWTON_LEWTON_H"
tab_width = 4
style = "Type"
language = "C"
